CREATE TABLE Usuario (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NombreUsuario NVARCHAR(50) NOT NULL,
    Correo NVARCHAR(100) NOT NULL,
    ContraseñaHash NVARCHAR(MAX) NOT NULL,
    Rol NVARCHAR(50) NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);